export const UPDATE_GRATITUDE = "UPDATE_GRATITUDE";
export const REMOVE_GRATITUDE = "REMOVE_GRATITUDE";
export const SET_CURRENT_GRATITUDE = "SET_CURRENT_GRATITUDE";
export const ADD_GRATITUDE = "ADD_GRATITUDE";
export const LOADING = "LOADING";


